//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int AlbumID { get; set; }
        public string AlbumName { get; set; }
        public string Description { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Photo { get; set; }
        public string TrackList { get; set; }
        public Nullable<bool> Grammy { get; set; }
        public int ArtistID { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
